language: java

notifications:
  irc: "irc.freenode.org#aerogear"

env:
    matrix:
      - ANDROID_SDKS=android-19 ANDROID_TARGET=android-19

before_install:

  # Download and configure newer version of maven
  - wget http://www.us.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
  - tar -zvxf apache-maven-3.1.1-bin.tar.gz;
  - export PATH=$PWD/apache-maven-3.1.1/bin:$PATH

  # Download the latest android sdk and unzip
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar -zxf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

  # Install required components.
  - echo y | android update sdk --filter $ANDROID_SDKS,platform-tools,extra-android-support,extra-google-google_play_services --no-ui --force --all
  - echo y | android update sdk -u -a -t 3,4

  # Checkout maven-android-sdk-deployer
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git

  # Install android maven repository
  - cd $PWD/maven-android-sdk-deployer/platforms/$ANDROID_TARGET
  - mvn  install -N --quiet
  - cd -

  # Install locally google-play-services
  - cd $PWD/maven-android-sdk-deployer/extras/google-play-services
  - mvn install -N --quiet
  - cd -

  # Install locally compatibility-v4
  - cd $PWD/maven-android-sdk-deployer/extras/compatibility-v4
  - mvn install -N --quiet
  - cd -

  # Checkout AeroGear Android (SNAPSHOT)
  - git clone git://github.com/aerogear/aerogear-android.git
  - cd $PWD/aerogear-android
  - mvn install -N --quiet  
  - cd -  
